name: ci-backend (Branches)

on:
    push:
        branches:
            - '**'
            - '!main'
        paths:
            - 'sgcmapi/**'
<<<<<<< HEAD
            
permissions:
    contents: write
jobs:
    main:
        name: CIworkflow Main
=======

permissions:
    contents: write

jobs:
    main:
        name: CI Workflow Main
>>>>>>> 52c4829c53608840561abe22d18b1f7bdb606831
        uses: ./.github/workflows/ci-backend.yml

    merge:
        needs: main
<<<<<<< HEAD
        runs-on: unbuntu-latest
=======
        runs-on: ubuntu-latest
>>>>>>> 52c4829c53608840561abe22d18b1f7bdb606831
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Merge
              uses: devmasx/merge-branch@v1.4.0
              with:
                type: now
                target_branch: main
<<<<<<< HEAD
                github_token: ${{github.token}}
=======
                github_token: ${{ github.token }}
>>>>>>> 52c4829c53608840561abe22d18b1f7bdb606831
